[server]
# Disable file watcher to prevent inotify limit errors
fileWatcherType = "none"

# Optional: set port
port = 8501

# Optional: allow CORS for external requests
enableCORS = true

# Optional: run headless (needed for cloud deployment)
headless = true

[theme]
base = "dark"
primaryColor = "#FFA500"
backgroundColor = "#222222"
secondaryBackgroundColor = "#333333"
textColor = "#FFFFFF"
