import streamlit as st
import requests
import io
import datetime
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors

# ================= CONFIG =================
OPENROUTER_API_KEY = st.secrets.get("OPENROUTER_API_KEY", "")
MODEL = "openai/gpt-4o-mini"
API_URL = "https://openrouter.ai/api/v1/chat/completions"
# ===========================================

st.set_page_config(page_title="Smart Cultural Storyteller", page_icon="🎭", layout="centered")

# ======== Theme State ========
if "theme" not in st.session_state:
    st.session_state["theme"] = "dark"

# Day/Night Toggle Icons
col1, col2 = st.sidebar.columns([1, 1])
with col1:
    if st.button("🌞 Light"):
        st.session_state["theme"] = "light"
with col2:
    if st.button("🌙 Dark"):
        st.session_state["theme"] = "dark"

accent_color = "#FF9800"  # Orange accent

# ======== Story Function ========
def generate_story(prompt, category):
    headers = {
        "Authorization": f"Bearer {OPENROUTER_API_KEY}",
        "Content-Type": "application/json"
    }

    story_type = {
        "Folk Tale": "You are a magical storyteller. Retell folk tales in a vivid, enchanting, and interactive way. Ensure the story has a bold title on the first line, and the story is at least 500 words with dialogues, plot, and rich details.",
        "Historical Event": "You are a historian. Retell historical events in an engaging and detailed storytelling manner. Include a bold title on the first line, context, characters, and vivid descriptions.",
        "Tradition": "You are a cultural guide. Explain traditions with stories and meaning in a detailed and captivating way. Include a bold title on the first line."
    }

    payload = {
        "model": MODEL,
        "messages": [
            {"role": "system", "content": story_type.get(category, story_type["Folk Tale"])},
            {"role": "user", "content": prompt}
        ],
        "max_tokens": 1500,
        "temperature": 0.8,
        "stream": False
    }

    response = requests.post(API_URL, headers=headers, json=payload)
    if response.status_code == 200:
        return response.json()['choices'][0]['message']['content']
    else:
        return f"Error: {response.status_code} - {response.text}"

# ======== PDF Export ========
def add_footer(canvas, doc):
    footer_text = f"Generated by Smart Cultural Storyteller – {datetime.date.today().strftime('%b %d, %Y')}"
    canvas.setFont("Helvetica-Oblique", 9)
    canvas.setFillColor(colors.HexColor("#FF9800"))
    canvas.drawCentredString(letter[0] / 2.0, 30, footer_text)

def create_pdf(story_text):
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter,
                            rightMargin=72, leftMargin=72,
                            topMargin=72, bottomMargin=72)

    styles = getSampleStyleSheet()

    # Split title & body
    story_lines = story_text.split("\n")
    title = story_lines[0].strip()
    body_lines = story_lines[1:]

    # Title style
    title_style = ParagraphStyle(
        "TitleStyle",
        parent=styles["Heading1"],
        fontName="Helvetica-Bold",
        fontSize=18,
        textColor=colors.HexColor("#FF9800"),
        alignment=1,  # center
        spaceAfter=20,
    )

    body_style = ParagraphStyle(
        "BodyStyle",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=12,
        leading=16,
        textColor=colors.black
    )

    story = []
    story.append(Paragraph(title, title_style))
    story.append(Spacer(1, 12))

    for line in body_lines:
        if line.strip():
            story.append(Paragraph(line.strip(), body_style))
            story.append(Spacer(1, 6))

    doc.build(story, onFirstPage=add_footer, onLaterPages=add_footer)
    buffer.seek(0)
    return buffer

# ======== Story Box Styling ========
if st.session_state["theme"] == "dark":
    story_bg = "#1e1e1e"
    story_text_color = "#FFFFFF"
    scrollbar_color = "#888"
else:
    story_bg = "#f9f9f9"
    story_text_color = "#000000"
    scrollbar_color = "#333"

st.markdown(
    f"""
    <style>
        .stApp {{
            background-color: #222222;  /* Always dark */
            color: #FFFFFF;
        }}
        .stButton button {{
            background-color: {accent_color};
            color: white;
            font-weight: bold;
            border-radius: 10px;
        }}
        .story-box {{
            overflow-y: auto;
            padding: 10px;
            background-color: {story_bg};
            border: 1px solid {accent_color};
            border-radius: 8px;
            color: {story_text_color};
        }}
    </style>
    """,
    unsafe_allow_html=True
)

# ======== UI ========
st.title("🎭 Smart Cultural Storyteller")
st.markdown("Retell **Folk Tales**, **Historical Events**, and **Traditions** with AI magic ✨")

# Sidebar Category
st.sidebar.header("Choose a Category")
category = st.sidebar.radio(
    "Pick one:",
    ["Folk Tale", "Historical Event", "Tradition"],
    format_func=lambda x: f"🌟 {x}" if x == "Folk Tale" else ("📜 "+x if x=="Historical Event" else "🎎 "+x)
)

# User input
prompt = st.text_input("Enter a prompt to begin your story:")

if "story" not in st.session_state:
    st.session_state["story"] = ""

if st.button("Generate Story"):
    if not prompt:
        st.warning("⚠️ Please enter a prompt first!")
    else:
        with st.spinner("Summoning your story... 🌌"):
            story = generate_story(prompt, category)
            st.session_state["story"] = story

if st.session_state["story"]:
    # Split title & body
    story_lines = st.session_state["story"].split("\n")
    title = story_lines[0].strip()
    body_lines = story_lines[1:]

    # Dynamically set story-box height
    story_length = len(body_lines)
    story_height = min(800, max(400, 30 * story_length))

    st.markdown(
        f"""
        <style>
            .story-box {{
                height: {story_height}px;
            }}
        </style>
        """,
        unsafe_allow_html=True
    )

    # Build HTML with bold centered title
    story_html = f"<div style='text-align:center; font-weight:bold; font-size:16px; margin-bottom:10px;'>{title}</div>"
    story_html += "<br>".join(body_lines)

    st.subheader("📖 Your Story:")
    st.markdown(f"<div class='story-box'>{story_html}</div>", unsafe_allow_html=True)

    # TXT download
    st.download_button(
        "📥 Download as TXT",
        data=st.session_state["story"].encode("utf-8"),
        file_name="story.txt",
        mime="text/plain",
        key="download-txt"
    )

    # PDF download
    pdf_buffer = create_pdf(st.session_state["story"])
    st.download_button(
        "📥 Download as PDF",
        data=pdf_buffer,
        file_name="story.pdf",
        mime="application/pdf",
        key="download-pdf"
    )
